### ISSUE TITLE
NoneType error on observer nodes

### ISSUE THREAD

**Issue by moosssees** [ohmu/pglookout#31]
I'm getting a constant NoneType error on observer nodes.  Looks like its trying to get the state of own_db which is none for observers.

Here's the stack trace:
Jul 26 14:53:04 ip-10-0-152-46 pglookout MainThread ERROR: Failed to check cluster state
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pglookout-1.3.1-py2.7.egg/pglookout/pglookout.py", line 583, in main_loop
    self.check_cluster_state()
  File "/usr/local/lib/python2.7/dist-packages/pglookout-1.3.1-py2.7.egg/pglookout/pglookout.py", line 303, in check_cluster_state
    self.emit_stats(own_state)
  File "/usr/local/lib/python2.7/dist-packages/pglookout-1.3.1-py2.7.egg/pglookout/pglookout.py", line 278, in emit_stats
    if self.is_restoring_or_catching_up_normally(state):
  File "/usr/local/lib/python2.7/dist-packages/pglookout-1.3.1-py2.7.egg/pglookout/pglookout.py", line 259, in is_restoring_or_catching_up_normally
    replication_start_time = state.get("replication_start_time")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Ormod** [comment]
Can you switch the logging to DEBUG (log_level config switch, you can even do it when it's running by sending a SIGHUP to the process) and attach a DEBUG log. Also the state file might be useful (in /tmp unless configured otherwise)

**Comment by moosssees** [comment]
Here are the requested files:
[pglookout.log.tar.gz](https://github.com/ohmu/pglookout/files/384314/pglookout.log.tar.gz)

[pglookout_state.json.tar.gz](https://github.com/ohmu/pglookout/files/384315/pglookout_state.json.tar.gz)

**Comment by Ormod** [comment]
Sorry for the long wait, finally got to take a look at the logs. 

Problem was with our statsd support trying to send replication_lag stats on observer nodes.. which obviously don't have any. Please let us know if you face any further problems.
